Fix parallel calls
matlab-deep-learning/llms-with-matlab pull request #22
Opened 2024-04-20 20:08 UTC by debymf

Rewriting the text of the example.

2024-04-22 10:02 UTC, vpapanasta commented on examples/AnalyzeTextDataUsingParallelFunctionCallwithChatGPT.mlx
Edit the third step sentence to something like:
"Create a function that extracts information about customers of a given gender and age range." ---> 

"Create a function that extracts information about customers."

2024-04-22 10:06 UTC, vpapanasta requested changes
Thanks Deborah. Leaving feedback just for the parallel function call example changes. Regarding the rest of the changes, I have left feedback in: https://github.com/matlab-deep-learning/llms-with-matlab/pull/23

2024-04-23 19:12 UTC, debymf commented on examples/AnalyzeTextDataUsingParallelFunctionCallwithChatGPT.mlx
Missed that! Thanks!

2024-04-24 10:37 UTC, vpapanasta approved these changes

2024-04-24 13:56 UTC, merged