Updated to support gpt-4o
matlab-deep-learning/llms-with-matlab pull request #33
Opened 2024-05-14 12:17 UTC by toshiakit

I updated README
openAIChat
and one example that contained a bug. 
All examples were tested and ran without errors.

2024-05-14 14:06 UTC, vpapanasta requested changes
It would be great to add a unit test for the new model in topenAIChat using a secret key. See as example the test point "createOpenAIChatWithOpenAIKey"

2024-05-15 07:59 UTC, toshiakit commented
> It would be great to add a unit test for the new model in topenAIChat using a secret key. See as example the test point "createOpenAIChatWithOpenAIKey"

Done

2024-05-15 08:01 UTC, toshiakit commented
> I have not reviewed the mlx file change.

There was an error when I tested the example. The variable name was renamed to "documents" except in one place and that caused the error.

2024-05-15 08:03 UTC, toshiakit commented on openAIChat.m
> +                if ~ismember(this.ModelName,["gpt-4-turbo","gpt-4-turbo-2024-04-09","gpt-4o","gpt-4o-2024-05-13"])
Please create a separate pull request to address this. This pull request is meant to bring this repo current with the latest OpenAI release.

2024-05-15 08:04 UTC, ccreutzi approved these changes
Thanks!

2024-05-15 08:40 UTC, vpapanasta commented on tests/topenAIChat.m
> +            testCase.verifyWarningFree(@()generate(chat, "Hello world."));
It is best to either create a new test point for "gpt-4o" or create a test parameter and with the default model value and the new "gpt-4o" one.

2024-05-15 08:41 UTC, vpapanasta reviewed
Thanks, Toshi, I left some extra feedback.

2024-05-15 10:44 UTC, toshiakit commented on tests/topenAIChat.m
> +            testCase.verifyWarningFree(@()generate(chat, "Hello world."));
I created a separate test point.

2024-05-15 10:48 UTC, vpapanasta approved these changes
Thanks for the changes Toshi.

2024-05-15 12:57 UTC, merged