Text only edits to error message catalog (doc review)
matlab-deep-learning/llms-with-matlab pull request #60
Opened 2024-07-25 14:42 UTC by MiriamScharnke

First batch of error message review, including those edits that required no further code changes.

2024-07-26 05:58 UTC, ccreutzi requested changes
Requesting change in `mustHaveMessages`.

2024-07-26 05:58 UTC, ccreutzi commented on +llms/+utils/errorMessageCatalog.m
> +catalog("llms:mustHaveMessages") = "Message must not be empty.";
An empty message in the list `Messages` would probably even be accepted. If you could get it in there.

```suggestion
catalog("llms:mustHaveMessages") = "Message history must not be empty.";
```

2024-07-26 05:58 UTC, ccreutzi commented on +llms/+utils/errorMessageCatalog.m
> +catalog("llms:functionNotAvailableForModel") = "This function is not supported for model ""{1}"".";
[Used in exactly one place](https://github.com/search?q=repo%3Amatlab-deep-learning%2Fllms-with-matlab%20llms%3AfunctionNotAvailableForModel&type=code), `openAIImages.edit`. I thought you wanted to make the text less generic for those cases?

```suggestion
catalog("llms:functionNotAvailableForModel") = "Image editing is not supported for model ""{1}"".";
```

2024-07-26 05:58 UTC, ccreutzi commented on +llms/+utils/errorMessageCatalog.m
> +catalog("llms:invalidContentTypeForModel") = "{1} is not supported for model ""{2}"".";
Only ever used with `"Image content"`. I guess that'll be changed when you also edit code?

2024-07-26 09:22 UTC, MiriamScharnke commented on +llms/+utils/errorMessageCatalog.m
> +catalog("llms:invalidContentTypeForModel") = "{1} is not supported for model ""{2}"".";
Yes :) But that's useful to know, thank you!

2024-07-29 06:41 UTC, ccreutzi approved these changes

2024-07-30 08:39 UTC, debymf approved these changes

2024-07-30 08:39 UTC, debymf commented on +llms/+utils/errorMessageCatalog.m
> +catalog("llms:mustBeMessagesOrTxt") = "Message must be nonempty string, character array, or messageHistory object.";
```suggestion
catalog("llms:mustBeMessagesOrTxt") = "Message must be nonempty string, character array, cell array of character vectors, or messageHistory object.";
```

2024-07-30 08:39 UTC, debymf commented on +llms/+utils/errorMessageCatalog.m
> +catalog("llms:mustBeMessagesOrTxt") = "Message must be nonempty string, character array, or messageHistory object.";
We also accept cell array of chars:
```
>> generate(mdl, {'hello'})

ans = 

    "Hello! How can I assist you today?"
```

2024-07-30 09:21 UTC, ccreutzi commented on +llms/+utils/errorMessageCatalog.m
> +catalog("llms:mustBeMessagesOrTxt") = "Message must be nonempty string, character array, or messageHistory object.";
We do not, however, accept arbitrary char arrays. (Plus, I have issue with calling chars “characters,” but I guess the doc standards just don't care about what I think. Not that they usually should.)

What's the proper doc term for a string that is not `""`? MATLAB does not regard `""` as “empty.”

2024-07-31 12:33 UTC, merged