Create functions directory in the doc folder and add openAIChat docum…
matlab-deep-learning/llms-with-matlab pull request #63
Opened 2024-07-29 14:25 UTC by MiriamScharnke

…entation.

2024-07-29 15:08 UTC, ccreutzi requested changes
I wish I could mark individual comments as “request change” or “just an aside, feel free to ignore.”

I think the only thing where I have a flag is the `Tools` documentation. Let me know if the functionality there is completely opaque – we didn't come up with the terminology.

2024-07-29 15:08 UTC, ccreutzi commented on doc/functions/openAIChat.md
> +modelName = "gpt-3.5-turbo";
We may not want to create new examples with 3.5. `"gpt-4o-mini"` is cheaper to use and generally considered on par or better.

2024-07-29 15:08 UTC, ccreutzi commented on doc/functions/openAIChat.md
> +-  [Analyze Sentiment in Text Using ChatGPT in JSON Mode](https://github.com/matlab-deep-learning/llms-with-matlab/blob/main/examples/AnalyzeSentimentinTextUsingChatGPTinJSONMode.md)
```suggestion
# See Also
-  [Create Simple Chat Bot](../../examples/CreateSimpleChatBot.md) 
-  [Process Generated Text in Real Time Using ChatGPT in Streaming Mode](../../examples/ProcessGeneratedTextinRealTimebyUsingChatGPTinStreamingMode.md) 
-  [Analyze Scientific Papers Using Function Calls](../../examples/AnalyzeScientificPapersUsingFunctionCalls.md) 
-  [Analyze Sentiment in Text Using ChatGPT in JSON Mode](../../examples/AnalyzeSentimentinTextUsingChatGPTinJSONMode.md) 
```

2024-07-29 15:09 UTC, ccreutzi commented on doc/functions/openAIChat.md
> +Instead of using the `APIKey` name\-value argument, you can also set the environment variable OPEN\_API\_KEY. For more information, see [https://github.com/matlab\-deep\-learning/llms\-with\-matlab/b
```suggestion
Instead of using the `APIKey` name\-value argument, you can also set the environment variable `OPEN_API_KEY`. For more information, see [the OpenAI overview documentation](../OpenAI.md).
```

2024-07-29 15:23 UTC, MiriamScharnke commented on doc/functions/openAIChat.md
> +# Properties
This is an on-going discussion in doc! 

The problem is that the name-value arguments and the properties overlap, but are not fully identical, nor is one a subset of the other. So the question becomes, how best to communicate this clearly? We want people to be able to tell easily what they can set via NV argument, and we also want people to tell easily what properties this object has.

A somewhat out-of-model option would be to have: 
Name-value arguments that do not correspond to properties
Properties settable at construction
Properties not settable at construction

This would have the advantage that no information would need to be repeated. For clarity, I could also add "chat = openAIChat(___,Property=value)" to the supported syntaxes. The disadvantage would be that this is out of model for the documentation. I'm not opposed to this, but would like to have a conversation about this in a team meeting. (I would also have to come up with better section titles - the above are just to illustrate the concept).

2024-07-29 16:15 UTC, MiriamScharnke commented on doc/functions/openAIChat.md
> +Instead of using the `APIKey` name\-value argument, you can also set the environment variable OPEN\_API\_KEY. For more information, see [https://github.com/matlab\-deep\-learning/llms\-with\-matlab/b
For the API credentials: yes, I think that is a very good idea, just not on this page! I have created an issue to keep track of the suggestion, and will think about how to incorporate it - probably actually in the main readme, or in all three <third-party-API>.md pages.

2024-07-30 06:49 UTC, ccreutzi commented on doc/functions/openAIChat.md
> +Connect to the OpenAI™ Chat Completion API to generate text using large language models developed by OpenAI.
Now we have the ™ twice on this page.
```suggestion
Connect to the OpenAI Chat Completion API to generate text using large language models developed by OpenAI.
```

2024-07-30 13:10 UTC, MiriamScharnke commented on doc/functions/openAIChat.md
> +Top probability mass for controlling the diversity of the generated output. Higher top probability mass corresponds to higher diversity.
How about "Top probability mass for controlling the diversity of the generated output using top-p sampling. Higher top probability mass corresponds to higher diversity."? This does not mention nucleus sampling, but top-p sampling should be googleable enough!

2024-08-01 10:44 UTC, MiriamScharnke commented on doc/functions/openAIChat.md
> +modelName = "gpt-3.5-turbo";
Fixed

2024-08-01 10:52 UTC, MiriamScharnke commented on doc/functions/openAIChat.md
> +Custom functions used by the model to process its input and output.
Fixed

2024-08-01 11:24 UTC, ccreutzi approved these changes

2024-08-01 11:24 UTC, ccreutzi commented on doc/functions/openAIChat.md
> +
Listing both seems potentially confusing.

2024-08-01 11:24 UTC, ccreutzi commented on doc/functions/openAIChat.md
> +`openAIFunction` object | array of `openAIFunction` objects
I thought doc agreed that scalars are arrays?

2024-08-01 11:24 UTC, ccreutzi commented on doc/functions/openAIChat.md
> +## Properties Settable at Construction
`Tools` is such a property, I think?

(Looks like I cannot give a proposal to submit because of the deleted line in between. I recommend moving “Tools” down into this section.)

2024-08-01 11:24 UTC, ccreutzi commented on doc/functions/openAIChat.md
>  `""` (default) | string array with between `1` and `4` elements
Why do we want the numbers in monospace? Also, the default is an empty string array, not the one-element string with no characters.

```suggestion
`[]` (default) | string array with between zero and four elements
```

2024-08-01 11:24 UTC, ccreutzi commented on doc/functions/openAIChat.md
> +---
These lines look heavier in the preview than the section break for “Properties Settable at Construction” below.

2024-08-01 11:24 UTC, ccreutzi commented on doc/functions/openAIChat.md
> +generate(chat,"Why is a raven like a writing desk?");
Generating text and discarding the output without saving it anywhere seems a bit pointless. Can we remove the semicolon?

2024-08-01 13:00 UTC, MiriamScharnke commented on doc/functions/openAIChat.md
> +
Fixed!

2024-08-01 13:02 UTC, MiriamScharnke commented on doc/functions/openAIChat.md
> +## Properties Settable at Construction
I don't think Tools is a property (so far as the user is concerned), only FunctionNames. You can't access "chat.Tools", for example ("No public property 'Tools' for class 'openAIChat'.").

2024-08-01 14:14 UTC, MiriamScharnke commented on doc/functions/openAIChat.md
>  `""` (default) | string array with between `1` and `4` elements
Fixed "" -> [] and 1 -> 0. The numbers are in monospace for consistency - if the string array had x elements, then x would be in monospace, too!

2024-08-01 14:15 UTC, MiriamScharnke commented on doc/functions/openAIChat.md
> +generate(chat,"Why is a raven like a writing desk?");
We can; do you want me to actually generate some text and also print the output?

2024-08-01 14:16 UTC, MiriamScharnke commented on doc/functions/openAIChat.md
> +`openAIFunction` object | array of `openAIFunction` objects
I agree this is technically redundant, but still think it's helpful (because otherwise users may think they have to put their single function object inside square brackets, for example).

2024-08-02 05:53 UTC, ccreutzi commented on doc/functions/openAIChat.md
> +## Properties Settable at Construction
Sorry, you're right. The `Tools` property is not exposed to the user, for whatever reason.

2024-08-02 05:54 UTC, ccreutzi commented on doc/functions/openAIChat.md
> +generate(chat,"Why is a raven like a writing desk?");
Possibly? Maybe faked or with an elision, so it doesn't get too long?

2024-08-09 12:06 UTC, closed without merging